fix AttributeError
When the ValueError exception should be raised, it raises instead:
AttributeError: 'str' object has no attribute 'name_of_path'
Because model_id_1 is a string, with no attribute 'name_of_path'